[CmdCtrlConfig]
ListenAddress = "0.0.0.0:4445"
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"
UseTLS = true
Enabled = true

[OortGroupStoreConfig]
ListenAddress = "0.0.0.0:6380"
MaxClients = 8192
Profile = false
Debug = false
InsecureSkipVerify = false
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"
CAFile = "/etc/oort/ca.pem"
MutualTLS = true

[GroupStoreConfig]
Scale = 0.1
CompactionInterval = 42
ValueCap = 4194302
Path = "/data"

[TCPMsgRingConfig]
UseTLS = true
MutualTLS = true
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"
CAFile = "/etc/oort/ca.pem"
